name: CD
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker images
        run: |
          docker build -t myorg/bar-back-backend ./backend
          docker build -t myorg/bar-back-frontend ./frontend
      - name: TODO Deploy
        run: echo "Deploy step goes here"
